
package se.pricer._interface.public_5_0;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PricerPublicAPI_5_0", targetNamespace = "http://public_5_0.interface.pricer.se/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PricerPublicAPI50 {


    /**
     * 
     * @param level
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isAlive", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.IsAlive")
    @ResponseWrapper(localName = "isAliveResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.IsAliveResponse")
    Boolean isAlive(
            @WebParam(name = "level", targetNamespace = "")
                    int level);

    /**
     * 
     * @param hostname
     * @param batch
     * @param printerName
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "print", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.Print")
    @ResponseWrapper(localName = "printResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.PrintResponse")
    String print(
            @WebParam(name = "batch", targetNamespace = "")
                    PrintBatch batch,
            @WebParam(name = "printerName", targetNamespace = "")
                    String printerName,
            @WebParam(name = "hostname", targetNamespace = "")
                    String hostname);

    /**
     * 
     * @param itemId
     * @return
     *     returns se.pricer._interface.public_5_0.Item
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItem", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetItemResponse")
    Item getItem(
            @WebParam(name = "itemId", targetNamespace = "")
                    String itemId);

    /**
     * 
     * @param homeSubcellId
     * @param linkOrder
     * @param barcode
     * @return
     *     returns se.pricer._interface.public_5_0.LinkStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unlink", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.Unlink")
    @ResponseWrapper(localName = "unlinkResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.UnlinkResponse")
    LinkStatus unlink(
            @WebParam(name = "barcode", targetNamespace = "")
                    String barcode,
            @WebParam(name = "homeSubcellId", targetNamespace = "")
                    String homeSubcellId,
            @WebParam(name = "linkOrder", targetNamespace = "")
                    Integer linkOrder);

    /**
     * 
     * @return
     *     returns se.pricer._interface.public_5_0.SystemVersion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSystemVersion", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetSystemVersion")
    @ResponseWrapper(localName = "getSystemVersionResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetSystemVersionResponse")
    SystemVersion getSystemVersion();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "refreshAllLabels", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.RefreshAllLabels")
    @ResponseWrapper(localName = "refreshAllLabelsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.RefreshAllLabelsResponse")
    String refreshAllLabels();

    /**
     * 
     * @param itemId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteItem", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.DeleteItem")
    @ResponseWrapper(localName = "deleteItemResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.DeleteItemResponse")
    String deleteItem(
            @WebParam(name = "itemId", targetNamespace = "")
                    String itemId);

    /**
     * 
     * @param items
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateItems", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.UpdateItems")
    @ResponseWrapper(localName = "updateItemsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.UpdateItemsResponse")
    String updateItems(
            @WebParam(name = "items", targetNamespace = "")
                    List<Item> items);

    /**
     * 
     * @param fileId
     * @return
     *     returns se.pricer._interface.public_5_0.UpdateStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUpdateStatus", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetUpdateStatus")
    @ResponseWrapper(localName = "getUpdateStatusResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetUpdateStatusResponse")
    UpdateStatus getUpdateStatus(
            @WebParam(name = "fileId", targetNamespace = "")
                    int fileId);

    /**
     * 
     * @param arg0
     * @return
     *     returns se.pricer._interface.public_5_0.PickList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPickList", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPickList")
    @ResponseWrapper(localName = "getPickListResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPickListResponse")
    PickList getPickList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.PickList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPickLists", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPickLists")
    @ResponseWrapper(localName = "getPickListsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPickListsResponse")
    List<PickList> getPickLists(
            @WebParam(name = "arg0", targetNamespace = "")
                    Page arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removePickList", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.RemovePickList")
    @ResponseWrapper(localName = "removePickListResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.RemovePickListResponse")
    String removePickList(
            @WebParam(name = "arg0", targetNamespace = "")
                    long arg0);

    /**
     * 
     * @param itemId
     * @param image
     * @param resize
     * @param updateTime
     * @param page
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postImage", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.PostImage")
    @ResponseWrapper(localName = "postImageResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.PostImageResponse")
    String postImage(
            @WebParam(name = "itemId", targetNamespace = "")
                    String itemId,
            @WebParam(name = "page", targetNamespace = "")
                    byte page,
            @WebParam(name = "image", targetNamespace = "")
                    byte[] image,
            @WebParam(name = "resize", targetNamespace = "")
                    int resize,
            @WebParam(name = "updateTime", targetNamespace = "")
                    Long updateTime);

    /**
     * 
     * @param subset
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNoOfESLs", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetNoOfESLs")
    @ResponseWrapper(localName = "getNoOfESLsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetNoOfESLsResponse")
    Integer getNoOfESLs(
            @WebParam(name = "subset", targetNamespace = "")
                    int subset);

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.TransceiverInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTransceivers", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetTransceivers")
    @ResponseWrapper(localName = "getTransceiversResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetTransceiversResponse")
    List<TransceiverInfo> getTransceivers(
            @WebParam(name = "name", targetNamespace = "")
                    String name);

    /**
     * 
     * @param barcodes
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "forceUpdate", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.ForceUpdate")
    @ResponseWrapper(localName = "forceUpdateResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.ForceUpdateResponse")
    String forceUpdate(
            @WebParam(name = "barcodes", targetNamespace = "")
                    List<String> barcodes);

    /**
     * 
     * @param linkInfo
     * @param itemId
     * @param barcode
     * @return
     *     returns se.pricer._interface.public_5_0.LinkStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "link", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.Link")
    @ResponseWrapper(localName = "linkResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.LinkResponse")
    LinkStatus link(
            @WebParam(name = "itemId", targetNamespace = "")
                    String itemId,
            @WebParam(name = "barcode", targetNamespace = "")
                    String barcode,
            @WebParam(name = "linkInfo", targetNamespace = "")
                    LinkInformation linkInfo);

    /**
     * 
     * @param globalParameter
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setGlobalParameter", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.SetGlobalParameter")
    @ResponseWrapper(localName = "setGlobalParameterResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.SetGlobalParameterResponse")
    String setGlobalParameter(
            @WebParam(name = "globalParameter", targetNamespace = "")
                    GlobalParameter globalParameter);

    /**
     * 
     * @param esls
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateLinkProperties", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.UpdateLinkProperties")
    @ResponseWrapper(localName = "updateLinkPropertiesResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.UpdateLinkPropertiesResponse")
    String updateLinkProperties(
            @WebParam(name = "esls", targetNamespace = "")
                    List<ESL> esls);

    /**
     * 
     * @return
     *     returns se.pricer._interface.public_5_0.UpdateStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastUpdateStatus", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLastUpdateStatus")
    @ResponseWrapper(localName = "getLastUpdateStatusResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLastUpdateStatusResponse")
    UpdateStatus getLastUpdateStatus();

    /**
     * 
     * @param esls
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEslProperties", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.UpdateEslProperties")
    @ResponseWrapper(localName = "updateEslPropertiesResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.UpdateEslPropertiesResponse")
    String updateEslProperties(
            @WebParam(name = "esls", targetNamespace = "")
                    List<ESL> esls);

    /**
     * 
     * @param itemIds
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItems", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetItems")
    @ResponseWrapper(localName = "getItemsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetItemsResponse")
    List<Item> getItems(
            @WebParam(name = "itemIds", targetNamespace = "")
                    List<String> itemIds);

    /**
     * 
     * @param limit
     * @param subset
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getESLs", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetESLs")
    @ResponseWrapper(localName = "getESLsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetESLsResponse")
    List<String> getESLs(
            @WebParam(name = "limit", targetNamespace = "")
                    Limit limit,
            @WebParam(name = "subset", targetNamespace = "")
                    int subset);

    /**
     * 
     * @param dataFileName
     * @return
     *     returns se.pricer._interface.public_5_0.UpdateStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastUpdateStatusByFileName", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLastUpdateStatusByFileName")
    @ResponseWrapper(localName = "getLastUpdateStatusByFileNameResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLastUpdateStatusByFileNameResponse")
    UpdateStatus getLastUpdateStatusByFileName(
            @WebParam(name = "dataFileName", targetNamespace = "")
                    String dataFileName);

    /**
     * 
     * @param barcode
     * @return
     *     returns se.pricer._interface.public_5_0.ESL
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getESL", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetESL")
    @ResponseWrapper(localName = "getESLResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetESLResponse")
    ESL getESL(
            @WebParam(name = "barcode", targetNamespace = "")
                    String barcode);

    /**
     * 
     * @return
     *     returns se.pricer._interface.public_5_0.BasicServerStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBasicServerStatus", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetBasicServerStatus")
    @ResponseWrapper(localName = "getBasicServerStatusResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetBasicServerStatusResponse")
    BasicServerStatus getBasicServerStatus();

    /**
     * 
     * @param globalParameters
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setGlobalParameters", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.SetGlobalParameters")
    @ResponseWrapper(localName = "setGlobalParametersResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.SetGlobalParametersResponse")
    String setGlobalParameters(
            @WebParam(name = "globalParameters", targetNamespace = "")
                    List<GlobalParameter> globalParameters);

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.GlobalParameter>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGlobalParameters", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetGlobalParameters")
    @ResponseWrapper(localName = "getGlobalParametersResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetGlobalParametersResponse")
    List<GlobalParameter> getGlobalParameters();

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.VersionEntry>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServerJarVersions", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetServerJarVersions")
    @ResponseWrapper(localName = "getServerJarVersionsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetServerJarVersionsResponse")
    List<VersionEntry> getServerJarVersions();

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.BackupConfiguration>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrcConfigurations", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPrcConfigurations")
    @ResponseWrapper(localName = "getPrcConfigurationsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPrcConfigurationsResponse")
    List<BackupConfiguration> getPrcConfigurations();

    /**
     * 
     * @param templateName
     * @return
     *     returns se.pricer._interface.public_5_0.PosterTemplateConfiguration
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPosterTemplateConfiguration", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPosterTemplateConfiguration")
    @ResponseWrapper(localName = "getPosterTemplateConfigurationResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPosterTemplateConfigurationResponse")
    PosterTemplateConfiguration getPosterTemplateConfiguration(
            @WebParam(name = "templateName", targetNamespace = "")
                    String templateName);

    /**
     * 
     * @param all
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReportNames", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetReportNames")
    @ResponseWrapper(localName = "getReportNamesResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetReportNamesResponse")
    List<String> getReportNames(
            @WebParam(name = "all", targetNamespace = "")
                    boolean all);

    /**
     * 
     * @param posterId
     * @return
     *     returns se.pricer._interface.public_5_0.Poster
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPoster", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPoster")
    @ResponseWrapper(localName = "getPosterResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPosterResponse")
    Poster getPoster(
            @WebParam(name = "posterId", targetNamespace = "")
                    String posterId);

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.SubcellInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllSubcells", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllSubcells")
    @ResponseWrapper(localName = "getAllSubcellsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllSubcellsResponse")
    List<SubcellInfo> getAllSubcells();

    /**
     * 
     * @param posterId
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.PosterItem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPosterItems", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPosterItems")
    @ResponseWrapper(localName = "getPosterItemsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPosterItemsResponse")
    List<PosterItem> getPosterItems(
            @WebParam(name = "posterId", targetNamespace = "")
                    String posterId);

    /**
     * 
     * @param name
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrcFile", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPrcFile")
    @ResponseWrapper(localName = "getPrcFileResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPrcFileResponse")
    byte[] getPrcFile(
            @WebParam(name = "name", targetNamespace = "")
                    String name);

    /**
     * 
     * @param configuration
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generatePrc", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GeneratePrc")
    @ResponseWrapper(localName = "generatePrcResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GeneratePrcResponse")
    String generatePrc(
            @WebParam(name = "configuration", targetNamespace = "")
                    BackupConfiguration configuration);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "forceUpdateAll", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.ForceUpdateAll")
    @ResponseWrapper(localName = "forceUpdateAllResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.ForceUpdateAllResponse")
    String forceUpdateAll();

    /**
     * 
     * @param linkStatus
     * @return
     *     returns se.pricer._interface.public_5_0.LinkStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLinkStatus", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLinkStatus")
    @ResponseWrapper(localName = "getLinkStatusResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLinkStatusResponse")
    LinkStatus getLinkStatus(
            @WebParam(name = "linkStatus", targetNamespace = "")
                    LinkStatus linkStatus);

    /**
     * 
     * @param itemId
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.ESL>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLinkedESLs", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLinkedESLs")
    @ResponseWrapper(localName = "getLinkedESLsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLinkedESLsResponse")
    List<ESL> getLinkedESLs(
            @WebParam(name = "itemId", targetNamespace = "")
                    String itemId);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "flashLedOn", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.FlashLedOn")
    @ResponseWrapper(localName = "flashLedOnResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.FlashLedOnResponse")
    String flashLedOn(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    boolean arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    boolean arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "flashLedOff", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.FlashLedOff")
    @ResponseWrapper(localName = "flashLedOffResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.FlashLedOffResponse")
    String flashLedOff(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    boolean arg1);

    /**
     * 
     * @param batchId
     * @return
     *     returns se.pricer._interface.public_5_0.PrintBatch
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrintBatch", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPrintBatch")
    @ResponseWrapper(localName = "getPrintBatchResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPrintBatchResponse")
    PrintBatch getPrintBatch(
            @WebParam(name = "batchId", targetNamespace = "")
                    int batchId);

    /**
     * 
     * @param batch
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "savePrintBatch", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.SavePrintBatch")
    @ResponseWrapper(localName = "savePrintBatchResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.SavePrintBatchResponse")
    Integer savePrintBatch(
            @WebParam(name = "batch", targetNamespace = "")
                    PrintBatch batch);

    /**
     * 
     * @param includeLinks
     * @param includeItems
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPfiBackup", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.CreatePfiBackup")
    @ResponseWrapper(localName = "createPfiBackupResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.CreatePfiBackupResponse")
    Boolean createPfiBackup(
            @WebParam(name = "includeItems", targetNamespace = "")
                    boolean includeItems,
            @WebParam(name = "includeLinks", targetNamespace = "")
                    boolean includeLinks);

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.PrintBatch>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPrintBatches", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllPrintBatches")
    @ResponseWrapper(localName = "getAllPrintBatchesResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllPrintBatchesResponse")
    List<PrintBatch> getAllPrintBatches();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.TaskToLightList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskToLightLists", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetTaskToLightLists")
    @ResponseWrapper(localName = "getTaskToLightListsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetTaskToLightListsResponse")
    List<TaskToLightList> getTaskToLightLists(
            @WebParam(name = "arg0", targetNamespace = "")
                    Page arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns se.pricer._interface.public_5_0.TaskToLightList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTaskToLightList", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetTaskToLightList")
    @ResponseWrapper(localName = "getTaskToLightListResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetTaskToLightListResponse")
    TaskToLightList getTaskToLightList(
            @WebParam(name = "arg0", targetNamespace = "")
                    long arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns se.pricer._interface.public_5_0.TaskToLightList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTaskToLightList", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.CreateTaskToLightList")
    @ResponseWrapper(localName = "createTaskToLightListResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.CreateTaskToLightListResponse")
    TaskToLightList createTaskToLightList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    List<String> arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    List<TaskToLightListTask> arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeTaskToLightList", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.RemoveTaskToLightList")
    @ResponseWrapper(localName = "removeTaskToLightListResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.RemoveTaskToLightListResponse")
    String removeTaskToLightList(
            @WebParam(name = "arg0", targetNamespace = "")
                    long arg0);

    /**
     * 
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLoginChallenge", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLoginChallenge")
    @ResponseWrapper(localName = "getLoginChallengeResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLoginChallengeResponse")
    String getLoginChallenge(
            @WebParam(name = "user", targetNamespace = "")
                    String user);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateReportUsingDefaultLocale", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GenerateReportUsingDefaultLocale")
    @ResponseWrapper(localName = "generateReportUsingDefaultLocaleResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GenerateReportUsingDefaultLocaleResponse")
    String generateReportUsingDefaultLocale(
            @WebParam(name = "name", targetNamespace = "")
                    String name);

    /**
     * 
     * @param hostname
     * @param printerName
     * @param batchId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "printByBatchId", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.PrintByBatchId")
    @ResponseWrapper(localName = "printByBatchIdResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.PrintByBatchIdResponse")
    String printByBatchId(
            @WebParam(name = "batchId", targetNamespace = "")
                    int batchId,
            @WebParam(name = "printerName", targetNamespace = "")
                    String printerName,
            @WebParam(name = "hostname", targetNamespace = "")
                    String hostname);

    /**
     * 
     * @param batchId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deletePrintBatch", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.DeletePrintBatch")
    @ResponseWrapper(localName = "deletePrintBatchResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.DeletePrintBatchResponse")
    String deletePrintBatch(
            @WebParam(name = "batchId", targetNamespace = "")
                    int batchId);

    /**
     * 
     * @param itemId
     * @param homeSubcellId
     * @return
     *     returns se.pricer._interface.public_5_0.LinkStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unlinkItem", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.UnlinkItem")
    @ResponseWrapper(localName = "unlinkItemResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.UnlinkItemResponse")
    LinkStatus unlinkItem(
            @WebParam(name = "itemId", targetNamespace = "")
                    String itemId,
            @WebParam(name = "homeSubcellId", targetNamespace = "")
                    String homeSubcellId);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPrinters", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllPrinters")
    @ResponseWrapper(localName = "getAllPrintersResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllPrintersResponse")
    List<String> getAllPrinters();

    /**
     * 
     * @param limit
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.Item>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemRange", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetItemRange")
    @ResponseWrapper(localName = "getItemRangeResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetItemRangeResponse")
    List<Item> getItemRange(
            @WebParam(name = "limit", targetNamespace = "")
                    Limit limit);

    /**
     * 
     * @param limit
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.ItemESLLink>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLinks", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllLinks")
    @ResponseWrapper(localName = "getAllLinksResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllLinksResponse")
    List<ItemESLLink> getAllLinks(
            @WebParam(name = "limit", targetNamespace = "")
                    Limit limit);

    /**
     * 
     * @param itemIds
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.ItemESLLinkList>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getItemLinks", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetItemLinks")
    @ResponseWrapper(localName = "getItemLinksResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetItemLinksResponse")
    List<ItemESLLinkList> getItemLinks(
            @WebParam(name = "itemIds", targetNamespace = "")
                    List<String> itemIds);

    /**
     * 
     * @param barcodes
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "refreshLabels", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.RefreshLabels")
    @ResponseWrapper(localName = "refreshLabelsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.RefreshLabelsResponse")
    String refreshLabels(
            @WebParam(name = "barcodes", targetNamespace = "")
                    List<String> barcodes);

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.ESLModel>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEslModels", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetEslModels")
    @ResponseWrapper(localName = "getEslModelsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetEslModelsResponse")
    List<ESLModel> getEslModels();

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.Poster>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllPosters", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllPosters")
    @ResponseWrapper(localName = "getAllPostersResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllPostersResponse")
    List<Poster> getAllPosters();

    /**
     * 
     * @param items
     * @param posterId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setPosterItems", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.SetPosterItems")
    @ResponseWrapper(localName = "setPosterItemsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.SetPosterItemsResponse")
    String setPosterItems(
            @WebParam(name = "posterId", targetNamespace = "")
                    String posterId,
            @WebParam(name = "items", targetNamespace = "")
                    List<PosterItem> items);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrcStatus", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPrcStatus")
    @ResponseWrapper(localName = "getPrcStatusResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPrcStatusResponse")
    String getPrcStatus(
            @WebParam(name = "name", targetNamespace = "")
                    String name);

    /**
     * 
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPfiBackup", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPfiBackup")
    @ResponseWrapper(localName = "getPfiBackupResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPfiBackupResponse")
    byte[] getPfiBackup();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns se.pricer._interface.public_5_0.PickList
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPickList", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.CreatePickList")
    @ResponseWrapper(localName = "createPickListResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.CreatePickListResponse")
    PickList createPickList(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    XMLGregorianCalendar arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    List<PickListItem> arg3);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLastError", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLastError")
    @ResponseWrapper(localName = "getLastErrorResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetLastErrorResponse")
    String getLastError();

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.BaseStationInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBasestations", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllBasestations")
    @ResponseWrapper(localName = "getAllBasestationsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllBasestationsResponse")
    List<BaseStationInfo> getAllBasestations();

    /**
     * 
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTotalNumberOfItems", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetTotalNumberOfItems")
    @ResponseWrapper(localName = "getTotalNumberOfItemsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetTotalNumberOfItemsResponse")
    Integer getTotalNumberOfItems();

    /**
     * 
     * @param itemIds
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "refreshLinkedLabels", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.RefreshLinkedLabels")
    @ResponseWrapper(localName = "refreshLinkedLabelsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.RefreshLinkedLabelsResponse")
    String refreshLinkedLabels(
            @WebParam(name = "itemIds", targetNamespace = "")
                    List<String> itemIds);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPfiBackupStatus", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPfiBackupStatus")
    @ResponseWrapper(localName = "getPfiBackupStatusResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetPfiBackupStatusResponse")
    String getPfiBackupStatus();

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.PropertyId>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllEslPropertyIds", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllEslPropertyIds")
    @ResponseWrapper(localName = "getAllEslPropertyIdsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllEslPropertyIdsResponse")
    List<PropertyId> getAllEslPropertyIds();

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.PropertyId>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllItemPropertyIds", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllItemPropertyIds")
    @ResponseWrapper(localName = "getAllItemPropertyIdsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllItemPropertyIdsResponse")
    List<PropertyId> getAllItemPropertyIds();

    /**
     * 
     * @return
     *     returns java.util.List<se.pricer._interface.public_5_0.PropertyId>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllLinkPropertyIds", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllLinkPropertyIds")
    @ResponseWrapper(localName = "getAllLinkPropertyIdsResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.GetAllLinkPropertyIdsResponse")
    List<PropertyId> getAllLinkPropertyIds();

    /**
     * 
     * @param user
     * @param authenticationToken
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testLoginToken", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.TestLoginToken")
    @ResponseWrapper(localName = "testLoginTokenResponse", targetNamespace = "http://public_5_0.interface.pricer.se/", className = "se.pricer._interface.public_5_0.TestLoginTokenResponse")
    Boolean testLoginToken(
            @WebParam(name = "user", targetNamespace = "")
                    String user,
            @WebParam(name = "authenticationToken", targetNamespace = "")
                    String authenticationToken);

}
