
package se.pricer._interface.public_5_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PricerPublicAPI_5_0", targetNamespace = "http://public_5_0.interface.pricer.se/", wsdlLocation = "http://localhost:11097/pricer_5_0?wsdl")
public class PricerPublicAPI50_Service
    extends Service
{

    private final static URL PRICERPUBLICAPI50_WSDL_LOCATION;
    private final static WebServiceException PRICERPUBLICAPI50_EXCEPTION;
    private final static QName PRICERPUBLICAPI50_QNAME = new QName("http://public_5_0.interface.pricer.se/", "PricerPublicAPI_5_0");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:11097/pricer_5_0?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRICERPUBLICAPI50_WSDL_LOCATION = url;
        PRICERPUBLICAPI50_EXCEPTION = e;
    }

    public PricerPublicAPI50_Service() {
        super(__getWsdlLocation(), PRICERPUBLICAPI50_QNAME);
    }

    public PricerPublicAPI50_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRICERPUBLICAPI50_QNAME, features);
    }

    public PricerPublicAPI50_Service(URL wsdlLocation) {
        super(wsdlLocation, PRICERPUBLICAPI50_QNAME);
    }

    public PricerPublicAPI50_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRICERPUBLICAPI50_QNAME, features);
    }

    public PricerPublicAPI50_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PricerPublicAPI50_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PricerPublicAPI50
     */
    @WebEndpoint(name = "PricerPublicAPI_5_0Port")
    public PricerPublicAPI50 getPricerPublicAPI50Port() {
        return super.getPort(new QName("http://public_5_0.interface.pricer.se/", "PricerPublicAPI_5_0Port"), PricerPublicAPI50.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PricerPublicAPI50
     */
    @WebEndpoint(name = "PricerPublicAPI_5_0Port")
    public PricerPublicAPI50 getPricerPublicAPI50Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://public_5_0.interface.pricer.se/", "PricerPublicAPI_5_0Port"), PricerPublicAPI50.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRICERPUBLICAPI50_EXCEPTION!= null) {
            throw PRICERPUBLICAPI50_EXCEPTION;
        }
        return PRICERPUBLICAPI50_WSDL_LOCATION;
    }

}
